services:
  enshrouded-server:
    build:
      context: .
      args:
        STEAM_USER: "steam"
        STEAM_HOME: "/home/steam"
        STEAM_USER_UID: "1000"
        STEAM_USER_GID: "1000"
        STEAMCMD_DIR: "/home/steam/steamcmd"
        STEAM_APP_DIR: "/home/steam/server"
        STEAM_COMPAT_DATA_PATH: "/home/steam/proton-compat"
        PROTON_VERSION: "GE-Proton10-26"

    image: enshrouded-server:latest
    container_name: enshrouded-server
    restart: unless-stopped
    ports:
      - "15637:15637/udp" # Query port
      - "27015:27015/udp" # Steam port
    environment:
      - STEAM_APP_ID=2278520
      - GAME_EXECUTABLE=enshrouded_server.exe
    volumes:
      - ./game_data:/home/steam/server
      - ./proton_data:/home/steam/proton-compat