services:
  abiotic-factor-server:
    build:
      context: .
      args:
        STEAM_USER: "steam"
        STEAM_HOME: "/home/steam"
        STEAM_USER_UID: "1000"
        STEAM_USER_GID: "1000"
        STEAMCMD_DIR: "/home/steam/steamcmd"
        STEAM_APP_DIR: "/home/steam/server"
        PROTON_VERSION: "GE-Proton10-28"

    image: abiotic-factor-server:latest
    container_name: abiotic-factor-server
    user: "1000:1000"
    ports:
      - "7777:7777/udp" # Game port
      - "27015:27015/udp" # Steam port
    environment:
      - STEAM_APP_ID=2857200
      - GAME_EXECUTABLE=AbioticFactor/Binaries/Win64/AbioticFactorServer-Win64-Shipping.exe
      - GAME_ARGS=-useperfthreads
    volumes:
      - ./game_data:/home/steam/server
